export const LOAD_PANTS_PRODUCT = 'LOAD_PANTS_PRODUCT';
export const LOADING_PAGE = 'LOADING_PAGE';
export const FAILD_LOADING =  'FAILD_LOADING';

export const LOAD_SHIRTS_PRODUCT = "LOAD_SHIRTS_PRODUCT";

export const LOAD_IMAGES_ARRIVALS = "LOAD_IMAGES_ARRIVALS";